# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class InvalidActionError(builtins.ValueError):
    r"""
    Raised when the action taken by an agent is invalid or when the number of actions provided is different from the number of agents.
    """
    ...

@typing.final
class InvalidLevelError(builtins.ValueError):
    r"""
    Raised when the level asked does not exist.
    """
    ...

@typing.final
class InvalidWorldStateError(builtins.ValueError):
    r"""
    Raised when the state of the world is invalid.
    """
    ...

@typing.final
class ParsingError(builtins.ValueError):
    r"""
    Raised when there is a problem while parsing a world string.
    """
    ...

