mod assumptions;
mod generator;
mod lasers;
mod movement;
mod utils;
mod var_pool;
pub type Literal = i32;
pub type Clause = Vec<Literal>;
pub use generator::ClauseGenerator;
pub use var_pool::{VarKey, VarPool};
