# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from lle import world
import typing
__all__ = [
    "ClauseGenerator",
    "SolveMode",
]

@typing.final
class ClauseGenerator:
    r"""
    Generates the SAT clauses (CNF, as lists of signed integer literals) used by
    `lle.solver.Solver` and decodes solver models back into joint-action plans.
    
    The constraint generation itself (agent movement, collisions, laser propagation and blocking)
    is implemented in Rust for performance; SAT solving remains delegated to Python (e.g.
    `pysat.solvers.Minisat22`). One generator can be reused across modes because domain clauses are
    cached independently from cooperation-specific support clauses.
    
    ```python
    from pysat.solvers import Minisat22
    from lle import World
    from lle.solver.clauses import ClauseGenerator
    
    world = World.level(1)
    gen = ClauseGenerator(world, t_max=20)
    clauses, assumptions = gen.generate(10, mode="standard", collect_gems=False)
    with Minisat22(bootstrap_with=clauses) as solver:
        if solver.solve(assumptions=assumptions):
            plan = gen.decode_plan(solver.get_model(), 10)
    ```
    """
    @property
    def t_max(self) -> builtins.int:
        r"""
        The maximum time step considered by this generator.
        """
    @property
    def solution_lower_bound(self) -> builtins.int:
        r"""
        A cheap admissible lower bound on the length of any valid plan: the maximum,
        over all agents, of the shortest walkable-path distance to the nearest exit
        regardless of lasers.
        """
    @property
    def n_vars(self) -> builtins.int:
        r"""
        The number of SAT variables allocated so far by this generator.
        """
    def __new__(cls, world: world.World, t_max: builtins.int) -> ClauseGenerator:
        r"""
        Build a clause generator for the given `world`, considering plans of length up to `t_max`.
        """
    def generate(self, t: builtins.int, mode: typing.Literal['standard', 'no-cooperation', 'no-asymmetric', 'no-mutual', 'no-fully-coupled', 'no-sequence', 'no-interdependence', 'no-convergence', 'no-divergence'] | builtins.str | SolveMode | None = None, collect_gems: builtins.bool = True) -> tuple[builtins.list[builtins.list[builtins.int]], builtins.list[builtins.int]]:
        r"""
        Generate the complete formula for horizon `t`: every clause and assumption needed to solve
        the problem, from step 0.
        
        # Parameters
        - `mode` accepts either a `SolveMode` instance or its canonical string (`"standard"`,
        `"no-cooperation"`, `"no-asymmetric"`, `"no-mutual"`, `"no-fully-coupled"`, `"no-sequence[-N]"`,
        `"no-interdependence[-N]"`, `"no-convergence[-N]"`, `"no-divergence[-N]"`)
        - `collect_gems` adds gem-collection clauses to the objective.
        
        The result depends only on the arguments: it does not read or affect any stream started
        with [`Self::start_delta_stream`]. Its output must not be mixed into a solver that is also
        fed by such a stream, since both assert an unconditional objective for `t`.
        
        For incremental SAT solving across an ascending sequence of horizons, use
        [`Self::start_delta_stream`] and [`Self::advance_delta_stream`] instead: they avoid
        re-transferring clauses the solver already has.
        
        # Returns
        - `(clauses, assumptions)` ready to be fed to a SAT solver.
        
        # Raises:
        - `ValueError`: if `mode` is invalid or its parameter is meaningless.
        """
    def start_delta_stream(self, mode: typing.Literal['standard', 'no-cooperation', 'no-asymmetric', 'no-mutual', 'no-fully-coupled', 'no-sequence', 'no-interdependence', 'no-convergence', 'no-divergence'] | builtins.str | SolveMode | None = None, collect_gems: builtins.bool = True) -> None:
        r"""
        Start a new incremental stream fixed to `mode` and `collect_gems`, replacing any stream
        started previously.
        
        Call this once per retained SAT solver instance, before the first
        [`Self::advance_delta_stream`] call for that solver. Starting a new stream (even with the
        same mode) always resets the incremental cursor, so pair one call to this method with one
        solver instance: reusing a solver across two streams, or a stream across two solvers, mixes
        up which clauses each solver has actually seen.
        
        # Parameters
        - `mode`, `collect_gems`: see [`Self::generate`]. Unlike `generate`, these are fixed for the
        whole stream: to change either, start a new stream (and, in practice, a new solver).
        
        # Raises:
          - `ValueError`: if `mode` is invalid or its parameter is meaningless.
        """
    def advance_delta_stream(self, t: builtins.int) -> tuple[builtins.list[builtins.list[builtins.int]], builtins.list[builtins.int]]:
        r"""
        Generate the clauses the active stream has not sent yet, through horizon `t`.
        
        Every returned clause can be kept permanently in the caller's solver. The returned
        assumptions select what is active right now: the horizon objective is conditional on a
        fresh literal, so a later call can switch to a different horizon's objective by assuming a
        different literal instead of retracting anything. Repeating the previous horizon returns no
        clause and the same assumptions.
        
        ```python
        gen.start_delta_stream(mode="standard")
        with Minisat22() as solver:
            for t in range(gen.solution_lower_bound, gen.t_max + 1):
                clauses, assumptions = gen.advance_delta_stream(t)
                solver.append_formula(clauses)
                if solver.solve(assumptions=assumptions):
                    plan = gen.decode_plan(solver.get_model(), t)
                    break
        ```
        
        # Returns
        - `(clauses, assumptions)` ready to be fed to a SAT solver.
        
        # Raises:
        - `ValueError`: if no stream is active, or `t` is smaller than the horizon of the
            previous call.
        """
    def objective(self, t: builtins.int, collect_gems: builtins.bool = False) -> tuple[builtins.list[builtins.list[builtins.int]], builtins.list[builtins.int]]:
        r"""
        Generate only the objective clauses for horizon `t`.
        
        # Returns
        `(clauses, [])`. Useful for callers that manage the SAT solver directly and want to
        append the objective separately.
        """
    def decode_plan(self, model: typing.Sequence[builtins.int], t_end: builtins.int) -> builtins.list[builtins.list[world.Action]]:
        r"""
        Decode a SAT model (as returned by `solver.get_model()`) into a joint-action plan
        of length `t_end`, i.e. a list of `t_end` joint actions (one action per agent).
        
        # Raises:
        - `ValueError`: if the model does not encode a coherent sequence of moves.
        """

@typing.final
class SolveMode:
    r"""
    The solving mode used by `ClauseGenerator`.
    
    Build one with the factory methods (`SolveMode.standard()`, `SolveMode.no_sequence(length=3)`,
    …) or parse one from its canonical string with `SolveMode.from_str("no-sequence-3")`. The
    available modes control which extra clauses and assumptions are emitted by `generate(t)`:
    
    - `standard()` — world rules only; agents may cooperate freely.
    - `no_cooperation()` — forbids any non-owner agent from occupying a laser span. Equivalent to
      treating every beam as permanently active.
    - `no_asymmetric()` — rules out plans where an agent helps someone without ever being helped.
    - `no_mutual()` — rules out plans where two agents each help the other.
    - `no_fully_coupled()` — requires at least one ordered pair of agents to lack help.
    - `no_sequence(length=2)` — rules out plans containing a non-decreasing-time temporal sequence of
      `length` help edges or more (`a → b → c` is a sequence of length 2).
    - `no_interdependence(order=2)` — rules out plans whose dependency graph contains a temporal
      closed trail with exactly `order` distinct agents. Timestamps are non-decreasing; agents and
      static arcs may repeat at later times, but temporal edges may not repeat. Other exact orders
      remain allowed. `no_interdependence(2)` coincides with `no_mutual()`.
    - `no_convergence(k=2)` — rules out plans where one beneficiary receives help from at least `k`
      distinct helpers.
    - `no_divergence(k=2)` — rules out plans where one helper helps at least `k` distinct
      beneficiaries. This is the outgoing dual of `no_convergence`.
    
    ```python
    from lle.solver.clauses import ClauseGenerator, SolveMode
    from lle import World
    
    gen = ClauseGenerator(World.level(6), t_max=21)
    for t in range(gen.solution_lower_bound, gen.t_max + 1):
        clauses, assumptions = gen.generate(t, mode=SolveMode.no_sequence(2))
        ...
    ```
    """
    @property
    def value(self) -> builtins.str:
        r"""
        The canonical string representation, inverse of `from_str` (e.g. `"no-sequence-3"`).
        Default parameters are rendered without a suffix (`"no-sequence"`, `"no-interdependence"`,
        `"no-convergence"`, `"no-divergence"`).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def standard() -> SolveMode:
        r"""
        World rules only; agents may cooperate freely.
        """
    @staticmethod
    def no_cooperation() -> SolveMode:
        r"""
        Forbid any non-owner agent from entering a laser span (every beam is treated as active).
        """
    @staticmethod
    def no_asymmetric() -> SolveMode:
        r"""
        Forbid plans where an agent helps someone without ever being helped by another agent.
        """
    @staticmethod
    def no_mutual() -> SolveMode:
        r"""
        Forbid plans where two agents each help the other.
        
        Equivalent to `SolveMode::no_interdependence(2)`.
        """
    @staticmethod
    def no_fully_coupled() -> SolveMode:
        r"""
        Require at least one ordered pair of distinct agents to lack a help event.
        """
    @staticmethod
    def no_sequence(length: builtins.int = 2) -> SolveMode:
        r"""
        Forbid any non-decreasing-time temporal sequence of `length` help edges or more. `length` must be `>= 2`.
        """
    @staticmethod
    def no_interdependence(order: builtins.int = 2) -> SolveMode:
        r"""
        Forbid any temporal closed trail with exactly `order` distinct agents. `order` must be `>= 2`.
        """
    @staticmethod
    def no_convergence(k: builtins.int = 2) -> SolveMode:
        r"""
        Forbid any beneficiary from receiving help from at least `k` distinct helpers. `k` must be `>= 2`.
        """
    @staticmethod
    def no_divergence(k: builtins.int = 2) -> SolveMode:
        r"""
        Forbid any helper from helping at least `k` distinct beneficiaries. `k` must be `>= 2`.
        """
    @staticmethod
    def from_str(value: typing.Literal['standard', 'no-cooperation', 'no-asymmetric', 'no-mutual', 'no-fully-coupled', 'no-sequence', 'no-interdependence', 'no-convergence', 'no-divergence'] | builtins.str) -> SolveMode:
        r"""
        Parse a canonical string (e.g. `"standard"`, `"no-sequence-3"`, `"no-divergence-3"`).
        
        `"no-sequence"`, `"no-interdependence"`, `"no-convergence"`, and `"no-divergence"` accept a
        `"-n"` suffix for their parameter. Their bare forms are aliases for the corresponding
        `"-2"` forms.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

