# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Agent",
]

@typing.final
class Agent:
    r"""
    An agent in the world.
    """
    @property
    def num(self) -> builtins.int:
        r"""
        The agent id.
        """
    @property
    def colour(self) -> builtins.int:
        r"""
        The agent's colour, which decides which laser beams it can block and cross.
        Several agents may share a colour.
        """
    @property
    def is_dead(self) -> builtins.bool:
        r"""
        Whether the agent is dead or not.
        """
    @property
    def is_alive(self) -> builtins.bool:
        r"""
        Whether the agent is alive or not.
        """
    @property
    def has_arrived(self) -> builtins.bool:
        r"""
        Whether the agent has reached an exit or not.
        """

