# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "InvalidActionError",
    "InvalidLevelError",
    "InvalidWorldStateError",
    "ParsingError",
    "SolverError",
]

class InvalidActionError(builtins.ValueError):
    r"""
    Raised when the action taken by an agent is invalid or when the number of actions provided is different from the number of agents.
    """
    ...

class InvalidLevelError(builtins.ValueError):
    r"""
    Raised when the level asked does not exist.
    """
    ...

class InvalidWorldStateError(builtins.ValueError):
    r"""
    Raised when the state of the world is invalid.
    """
    ...

class ParsingError(builtins.ValueError):
    r"""
    Raised when there is a problem while parsing a world string.
    """
    ...

class SolverError(builtins.ValueError):
    r"""
    Raised when the solver encounters an illegal state.
    """
    ...

