# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from lle import world
import typing
__all__ = [
    "ClauseGenerator",
]

@typing.final
class ClauseGenerator:
    r"""
    Generates the SAT clauses (CNF, as lists of signed integer literals) used by
    `lle.solver.solve` and decodes solver models back into joint-action plans.
    
    The constraint generation itself (agent movement, collisions, laser propagation
    and blocking, objective) is implemented in Rust for performance; SAT solving
    remains delegated to Python (e.g. `pysat.solvers.Minisat22`).
    
    ```python
    from pysat.solvers import Minisat22
    from lle import World
    from lle.solver.constraints import ClauseGenerator
    
    world = World.level(1)
    gen = ClauseGenerator(world, t_max=20)
    clauses = [c for t in range(gen.t_max + 1) for c in gen.generate(t)]
    with Minisat22(bootstrap_with=clauses) as solver:
        solver.append_formula(gen.objective(gen.t_max))
        if solver.solve():
            plan = gen.decode_plan(solver.get_model(), gen.t_max)
    ```
    """
    @property
    def t_max(self) -> builtins.int:
        r"""
        The maximum time step considered by this generator.
        """
    @property
    def solution_lower_bound(self) -> builtins.int:
        r"""
        A cheap admissible lower bound on the length of any valid plan: the maximum,
        over all agents, of the shortest walkable-path distance to the nearest exit.
        """
    def __new__(cls, world: world.World, t_max: builtins.int) -> ClauseGenerator:
        r"""
        Build a clause generator for the given `world`, considering plans of length up to `t_max`.
        """
    def generate(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate every clause (initialization, movement and laser constraints) that applies
        at time step `t`. Clauses are returned as lists of signed integer literals (CNF),
        ready to be fed to a `pysat` solver.
        """
    def objective(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the objective clauses for time step `t`: every agent must be on an exit.
        Intended to be appended to the formula of the solver instance considering `t_end = t`.
        """
    def assume_no_cooperation(self, t: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Generate the unit clauses implementing strict (no-cooperation) laser mode at time `t`:
        since beams can never be blocked, every beam tile is permanently active, so no agent of a
        *different* colour may ever stand on one. The laser's own colour is immune and may still
        walk through its own beam.
        Generate the literal values assignments that corresponds to the assumption that no cooperation
        ever occurs at time step `t`.
        
        Raises:
            - `SolverError` if the cooperation variables are not yet created.
        """
    def cooperation_clauses(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the cooperation-tracking clauses for time step `t`: the `laser_blocked` and
        `coop_event` indicator-variable definitions.
        
        These are additive to `generate(t)` (they introduce new variables referencing the same
        per-step agent variables) and are only needed when reasoning about who helps whom, e.g.
        by `lle.cooperation.characterize`.
        """
    def decode_plan(self, model: typing.Sequence[builtins.int], t_end: builtins.int) -> builtins.list[builtins.list[world.Action]]:
        r"""
        Decode a SAT model (as returned by `solver.get_model()`) into a joint-action plan
        of length `t_end`, i.e. a list of `t_end` joint actions (one action per agent).
        
        Raises:
            `ValueError`: if the model does not encode a coherent sequence of moves.
        """

