# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from lle import world
import typing
__all__ = [
    "ClauseGenerator",
]

@typing.final
class ClauseGenerator:
    r"""
    Generates the SAT clauses (CNF, as lists of signed integer literals) used by
    `lle.solver.solve` and decodes solver models back into joint-action plans.
    
    The constraint generation itself (agent movement, collisions, laser propagation
    and blocking, objective) is implemented in Rust for performance; SAT solving
    remains delegated to Python (e.g. `pysat.solvers.Minisat22`).
    
    ```python
    from pysat.solvers import Minisat22
    from lle import World
    from lle.solver.constraints import ClauseGenerator
    
    world = World.level(1)
    gen = ClauseGenerator(world, t_max=20)
    clauses = [c for t in range(gen.t_max + 1) for c in gen.generate(t)]
    with Minisat22(bootstrap_with=clauses) as solver:
        solver.append_formula(gen.objective(gen.t_max))
        if solver.solve():
            plan = gen.decode_plan(solver.get_model(), gen.t_max)
    ```
    """
    @property
    def t_max(self) -> builtins.int:
        r"""
        The maximum time step considered by this generator.
        """
    @property
    def solution_lower_bound(self) -> builtins.int:
        r"""
        A cheap admissible lower bound on the length of any valid plan: the maximum,
        over all agents, of the shortest walkable-path distance to the nearest exit.
        """
    def __new__(cls, world: world.World, t_max: builtins.int) -> ClauseGenerator:
        r"""
        Build a clause generator for the given `world`, considering plans of length up to `t_max`.
        """
    def generate(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate every clause (initialization, movement and laser constraints) that applies
        at time step `t`. Clauses are returned as lists of signed integer literals (CNF),
        ready to be fed to a `pysat` solver.
        """
    def objective(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the objective clauses for time step `t`: every agent must be on an exit.
        Intended to be appended to the formula of the solver instance considering `t_end = t`.
        """
    def no_blocking_clauses(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the unit clauses implementing strict (no-cooperation) laser mode at time `t`:
        since beams can never be blocked, every beam tile is permanently active, so no agent of a
        *different* colour may ever stand on one. The laser's own colour is immune and may still
        walk through its own beam.
        
        Adding these clauses for every `t` in `[0, t_max]` makes the formula UNSAT iff laser
        blocking (cooperation) is required to solve the level within the horizon.
        """
    def assume_no_cooperation(self, t: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Generate the unit clauses assuming no cooperation is required between agents.
        
        # Raises
            - `SolverError` if the cooperation variables are not yet created.
        """
    def coop_clauses(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the cooperation-tracking clauses for time step `t`: the `laser_blocked` and
        `coop_event` indicator-variable definitions.
        
        These are additive to `generate(t)` (they introduce new variables referencing the same
        per-step agent variables) and are only needed when reasoning about who helps whom, e.g.
        by `lle.cooperation.characterize`.
        """
    def finalize_depends_on(self, t_end: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the `depends_on(beneficiary, helper)` definition clauses over the horizon
        `[0, t_end]`.
        
        Call this once per candidate horizon, after `coop_clauses(t)` has been generated for every
        `t` in `[0, t_end]`. The clauses depend on `t_end`, so feed them to the solver for that
        horizon only; do not accumulate them across horizons.
        """
    def depends_on_lit(self, beneficiary: builtins.int, helper: builtins.int) -> typing.Optional[builtins.int]:
        r"""
        The SAT literal for `depends_on(beneficiary, helper)`, or `None` when no such variable
        exists (the dependency can never occur within the horizon last passed to
        `finalize_depends_on`). Never creates a variable, so the returned literal is safe to use as
        a solver assumption.
        """
    def chain_clauses(self, t: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate the temporal chain-tracking clauses for time step `t`.
        
        Must be called after `coop_clauses(t)` for the same `t`. Defines:
        
        - `first_helped_by_time(a, b, t)` — "a has helped b at any time ≤ t" (running OR)
        - `chain_event(a, b, c, t)` — "a helped b at some time ≤ t-1 AND b helps c at t"
        
        These are used by `finalize_chain` to define the per-horizon `chain(a, b, c)` variables.
        """
    def finalize_chain(self, t_end: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate `chain(a, b, c)` definition clauses over the horizon `[0, t_end]`.
        
        Call once per candidate horizon, after `chain_clauses(t)` has been called for every
        `t ≤ t_end`. Feed the result to the solver for that horizon only.
        """
    def chain_lit(self, a: builtins.int, b: builtins.int, c: builtins.int) -> typing.Optional[builtins.int]:
        r"""
        The SAT literal for `chain(a, b, c)` — "a helped b strictly before b helped c" — or
        `None` if no such chain can occur within the horizon last passed to `finalize_chain`.
        """
    def finalize_mutual(self, t_end: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Generate `mutual(a, b)` definition clauses for the current horizon.
        
        Must be called after `finalize_depends_on(t_end)` for the same horizon (it reads the
        `depends_on` variables created by that call). Feed the result to the solver together
        with the `finalize_depends_on` output.
        """
    def mutual_lit(self, a: builtins.int, b: builtins.int) -> typing.Optional[builtins.int]:
        r"""
        The SAT literal for `mutual(a, b)` — "agents a and b mutually depend on each other" —
        or `None` if at least one direction of help is impossible within the current horizon.
        """
    def decode_plan(self, model: typing.Sequence[builtins.int], t_end: builtins.int) -> builtins.list[builtins.list[world.Action]]:
        r"""
        Decode a SAT model (as returned by `solver.get_model()`) into a joint-action plan
        of length `t_end`, i.e. a list of `t_end` joint actions (one action per agent).
        
        Raises:
            `ValueError`: if the model does not encode a coherent sequence of moves.
        """

