# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from lle import world
import numpy
import numpy.typing
import typing
__all__ = [
    "Layered",
    "PartialGenerator",
    "StateGenerator",
]

@typing.final
class Layered:
    @property
    def shape(self) -> tuple[builtins.int, builtins.int, builtins.int]: ...
    def __new__(cls, world: world.World, padding_size: typing.Optional[builtins.int] = None) -> Layered: ...
    def observe(self, world: world.World) -> numpy.typing.NDArray[numpy.float32]: ...
    def __deepcopy__(self, _memo: dict) -> Layered: ...

@typing.final
class PartialGenerator:
    def __new__(cls, world: world.World, size: builtins.int) -> PartialGenerator: ...
    def observe(self, world: world.World) -> numpy.typing.NDArray[numpy.float32]: ...
    def __deepcopy__(self, _memo: dict) -> PartialGenerator: ...

@typing.final
class StateGenerator:
    def __new__(cls, world: world.World, normalize: builtins.bool = False) -> StateGenerator: ...
    def observe(self, world: world.World) -> numpy.typing.NDArray[numpy.float32]: ...
    def __deepcopy__(self, _memo: dict) -> StateGenerator: ...

